spring:
    datasource:
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver

    jpa:
        show-sql: true
        hibernate.ddl-auto: update

endpoints:
    actuator:
        sensitive: false

server:
    port: 9000

management:
    port: 9001

    security:
        enabled: false
