spring:
    datasource:
#        url: jdbc:hsqldb:mem:dbtest
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
#        username: SA


    jpa:
        show-sql: true
        hibernate.ddl-auto: update

