INSERT INTO STOCK (BRAND, NAME, QUANTITY) VALUES ('Philips', 'Item2', 3);

INSERT INTO PRINCIPAL (USER, PASSWORD, IS_ADMIN) VALUES ('admin', 'admin', true);
INSERT INTO PRINCIPAL (USER, PASSWORD, IS_ADMIN) VALUES ('user', 'user', false);

